//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public int ProductPriceId { get; set; }
        public long ProductPricePurch { get; set; }
        public long ProductPriceSell { get; set; }
        public string ProductPriceDesc { get; set; }
        public int ProductId { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
