//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Customer
    {
        public string UserName { get; set; }
        public string UserFamily { get; set; }
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerTel { get; set; }
        public string CustomerAddress { get; set; }
        public int UserID { get; set; }
        public string FullName { get; set; }
        public Nullable<byte> CustomerActive { get; set; }
    }
}
